[package]
name = "access"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "=0.10.8"
rpassword = "7.3.1"

aes = "0.7.5"
cipher = "0.4.4"  

block-padding = "=0.2.1"

hex = "0.4.3"
base64 = "=0.22.1"

block-modes="0.8.1"
hex-literal="0.3.3"